### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by concon121** [jacob-meacham/serverless-plugin-deploy-environment#6]
Your main attribute is set incorrectly:

```
"main": "lib/index.js"
```

should be:

```
"main": "src/index.js"
```

**Comment by jacob-meacham** [comment]
lib should exist, I published 1.0.2 without a lib/ directory unfortunately. I've just released 1.0.3 that hopefully solves the issue. Let me know!

**Comment by robizz** [comment]
HI!
good work with this plugin, keep it up!

unfortunately you have published on npm only the 1.0.2, I have managed to install via tag the 1.0.3 but serverless still does not find the plugin main, changing the package.json from "main": "lib/index.js"
to "main": "src/index.js" solves the issue

maybe am I missing something?

thanks!

Roberto

**Comment by jacob-meacham** [comment]
Hi @robizz sorry for not publishing! 1.0.3 should be published now.

src/index.js uses es2016 + esnext imports so if you're already using babel then that will work fine. lib/index.js is the transformed code and I forgot to publish it for the 1.0.2 release.

Alternatively, if you want to run from source, you can run `npm run build` to generate lib/index.js.

Let me know if the published 1.0.3 works for you!
